##------------------------------------------------------------------
##------DB CONFIGURATION--------------------------------------------
##------------------------------------------------------------------
spring:
  data:
    mongodb:
      uri: mongodb://localhost/smartrent2
      database: smartrent2

##------------------------------------------------------------------
##------EXTERNAL REST SERVICES CONFIGURATION------------------------
##------------------------------------------------------------------
rest:
  service:
    user: http://user-service

##------------------------------------------------------------------
##------LOGGER CONFIGURATION----------------------------------------
##------------------------------------------------------------------
logging:
  file:
    path: logs
    name: user.log
    max-size: 10MB
  level:
    com.mg: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot: ERROR


